# -*- coding: utf-8 -*-
"""2303A52003_assignment-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxlZTmjzXrjLF5t1LEztjy9dZ86R8EZ3
"""



l1=[1,2,3,4,5]
 l2=[2,3,4,5,6]
 l3=l1+l2
 print(l3)
#print(l1)
#print(l2)

import numpy as np

import numpy as np
a=np.array(l1)
b=np.array(l2)
print(a+b)

print(np.mean(a))

print(np.median(a))

print(max(a)-min(a))

m=[[1,2,4],[2,3,4],[3,4,5]]
print(m)

m=np.array(m)
print(m)

m1=[[2,3,4],[3,5,7],[5,6,7]]
print(m1)

m1=np.array(m1)
print(m1)

print(m*m1)

print(m+m1)

b=np.matmul(m,m1)
print(b)

s=np.matrix.transpose(m)
print(s)

n=np.matrix.trace(m)
print(n)

p=np.linalg.det(m)
print(p)

w=np.linalg.inv(m)

print(w)

print(np.linalg.eig(m))

print(np.linalg.matrix_power(m,2))